variables:
  DOCKER_HUB_IMAGE: segescginf/pgdpetrvs
  DOCKER_HUB_TAG: latest
  SSH_USER: root
  SSH_HOST: 200.152.38.137
  SSH_PORT: 7225
  SSH_PASSWORD: dataprev12345
  DEPLOY_PATH: ./
  DOCKER_HUB_USERNAME: segescginf
  DOCKER_HUB_PASSWORD: dckr_pat_1JrKXQ3MUfthx_nZri5gq_wgjqo

services:
  - docker:dind

stages:
  - build_prod
  - deploy_prod

before_script:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

build_prod:
  stage: build_prod
  image: docker:latest
  script:
    - docker build -t $DOCKER_HUB_IMAGE:$DOCKER_HUB_TAG -f resources/dataprev/prod/Dockerfile .
    - docker push $DOCKER_HUB_IMAGE:$DOCKER_HUB_TAG
  only:
    - dataprev_prod

deploy_prod:
  stage: deploy_prod
  before_script:
    - apt-get update -y && apt-get install -y sshpass
  script:
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "sh install-pgd.sh"
  only:
    - dataprev_prod