version: "3.9"
services:

  petrvs_db:
    image: mysql:8
    container_name: petrvs_db
    ports:
      - 3308:3308
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: PsEeTnRhVaS
      MYSQL_USER: petrvs
      MYSQL_PASSWORD: PsEeTnRhVaS
      MYSQL_TCP_PORT: 3308
      TZ: "America/Bahia"
    deploy:
      resources:
        limits:
          memory: 1024M
      
  petrvs_php:
    build:
      context: .
      dockerfile: Dockerfile-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: petrvs_php
    working_dir: /var/www
    environment:
      - TZ=America/Bahia
    ports:
      - "80:80"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - petrvs_db
    volumes:
      - ../../../back-end:/var/www
    deploy:
      resources:
        limits:
          memory: 1024M
 

  petrvs_node:
    build:
      context: .
      dockerfile: Dockerfile-node
    container_name: petrvs_node
    command: sh -c "sleep infinity"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - TZ=America/Bahia
    ports:
      - "4200:4200"
    dns:
      - 1.1.1.1
    depends_on:
      - petrvs_php
    volumes:
      - ../../../front-end:/usr/src/app
      - ../../../back-end:/usr/src/back-end
