version: "3.9"
services:

  db:
    image: mysql:8
    container_name: db
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_USER: petrvs
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_TCP_PORT: 3308
      SERVICE_NAME: mysql
    secrets:
    - db_password
    - db_root_password

  php:
    build: 
      context: .
      dockerfile: Dockerfile-php
    container_name: php
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    volumes:
      - ../../../back-end:/var/www

secrets:
  db_password:
    file: ./configuracoes/db/db_password.txt
  db_root_password:
    file: ./configuracoes/db/db_root_password.txt