name: BuildDeploy Dataprev DSV

env:
  DOCKER_HUB_IMAGE: segescginf/pgdpetrvs
  DOCKER_HUB_TAG: dsv
  SSH_USER: root
  SSH_HOST: 200.152.38.137
  SSH_PORT: 7223
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD_DSV }}
  DEPLOY_PATH: ./
  DOCKER_HUB_USERNAME: segescginf
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build_dsv:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push docker image LATEST
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: TAG_NAME=$DOCKER_HUB_TAG
          tags: $DOCKER_HUB_IMAGE:latest

  deploy_dsv:
    runs-on: ubuntu-latest
    needs: build_dsv
    steps:
      - name: Install sshpass
        run: sudo apt-get update -y && sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          sshpass -p $SSH_PASSWORD ssh -T -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "sh install-pgd.sh < /dev/null"
