name: CI/CD

on:
  push:
    branches:
      - main
      - dataprev_dsv
      - dataprev_hmg
  pull_request:
    branches:
      - main
      - dataprev_dsv
      - dataprev_hmg

jobs:
  include:
    - name: "Build Deploy on Dataprev DSV"
      if: github.ref == 'refs/heads/dataprev_dsv'
      uses: ./.github/workflows/build_deploy_dsv.yml

    - name: "Build Deploy on Dataprev HMG"
      if: github.ref == 'refs/heads/dataprev_hmg'
      uses: ./.github/workflows/build_deploy_hmg.yml